# This file was generated by GoReleaser. DO NOT EDIT.
cask "gelf-pretty" do
  name "gelf-pretty"
  desc "CLI to pretty-print Graylog Extended Log Format (GELF) log lines"
  homepage "https://github.com/joaodrp/gelf-pretty"
  version "0.1.2"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "gelf-pretty"

  on_macos do
    on_intel do
      url "https://github.com/joaodrp/gelf-pretty/releases/download/v#{version}/gelf-pretty_#{version}_Darwin_x86_64.tar.gz"
      sha256 "7fc3bad76fb659167de403adf092e0632354cc68fa649a8a15a66bf655118e63"
    end
    on_arm do
      url "https://github.com/joaodrp/gelf-pretty/releases/download/v#{version}/gelf-pretty_#{version}_Darwin_arm64.tar.gz"
      sha256 "7838f816f43ca9f6cd5bed2c1ee2cdf670c92ff08d0143b400b53677f2a82eac"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/joaodrp/gelf-pretty/releases/download/v#{version}/gelf-pretty_#{version}_Linux_x86_64.tar.gz"
      sha256 "7f892254d7207b812904d0e53f29c0d1daa025969e4ff08f10d3a64d28ad784a"
    end
    on_arm do
      url "https://github.com/joaodrp/gelf-pretty/releases/download/v#{version}/gelf-pretty_#{version}_Linux_arm64.tar.gz"
      sha256 "da6b82e6b9768e3a902405d910f1ac4cc9c6923c421042e87b181643e29f5a0c"
    end
  end

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/gelf-pretty"]
    end
  end

  # No zap stanza required
end
