# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class GelfPretty < Formula
  desc "CLI to pretty-print Graylog Extended Log Format (GELF) log lines"
  homepage "https://github.com/joaodrp/gelf-pretty"
  version "0.1.1"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/joaodrp/gelf-pretty/releases/download/v0.1.1/gelf-pretty_0.1.1_Darwin_x86_64.tar.gz"
      sha256 "2979438b2ea0c9a06d8d8371e9b91162178248063dc0de69ae5ab1f75633a8ce"

      def install
        bin.install "gelf-pretty"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/joaodrp/gelf-pretty/releases/download/v0.1.1/gelf-pretty_0.1.1_Darwin_arm64.tar.gz"
      sha256 "9db4d2030cd5050be604cdd9619484098e7500a5a87502ce3eaff3d3de015b75"

      def install
        bin.install "gelf-pretty"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/joaodrp/gelf-pretty/releases/download/v0.1.1/gelf-pretty_0.1.1_Linux_x86_64.tar.gz"
      sha256 "badd7c13834bb56967c313d077522b63caca45831647b955d8156fa6c5ffe3c4"
      def install
        bin.install "gelf-pretty"
      end
    end
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/joaodrp/gelf-pretty/releases/download/v0.1.1/gelf-pretty_0.1.1_Linux_armv6.tar.gz"
      sha256 "9c40eb412b56d798f457258f29a83dea1c1cf8209613f54f486177cd4b8f32cd"
      def install
        bin.install "gelf-pretty"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/joaodrp/gelf-pretty/releases/download/v0.1.1/gelf-pretty_0.1.1_Linux_arm64.tar.gz"
      sha256 "a1f1bcf1b112e6c7d4354ae91287d2fb11edc22751c8ea26173ec383a8ea2ec2"
      def install
        bin.install "gelf-pretty"
      end
    end
  end

  test do
    system "#{bin}/gelf-pretty --version"
  end
end
