# This file was generated by GoReleaser. DO NOT EDIT.
class GelfPretty < Formula
  desc "CLI to pretty-print Graylog Extended Log Format (GELF) log lines"
  homepage "https://github.com/joaodrp/gelf-pretty"
  url "https://github.com/joaodrp/gelf-pretty/releases/download/v0.1.0/gelf-pretty_0.1.0_Darwin_x86_64.tar.gz"
  version "0.1.0"
  sha256 "934892fcab183259dbffced84a3d02717ddc4972a59c5a28bd9b200e7ac8ec0c"

  def install
    bin.install "gelf-pretty"
  end

  test do
    system "#{bin}/gelf-pretty --version"
  end
end
